<?php
declare(strict_types=1);

namespace App\Controller\Admin\V1;

use App\Service\Admin\AdminService;
use Hyperf\Di\Annotation\Inject;
use Hyperf\HttpServer\Annotation\Controller;
use Hyperf\HttpServer\Annotation\Middleware;
use App\Middleware\AuthMiddleware;
use Hyperf\HttpServer\Annotation\RequestMapping;
use Hyperf\HttpServer\Contract\RequestInterface;

/**
 * @Controller()
 * @Middleware(AuthMiddleware::class)
 * Class AdminController
 * @package App\Controller\Admin\V1
 */
class AdminController extends BaseController
{
    /**
     * @Inject()
     * @var AdminService
     */
    public $service;

    /**
     * @RequestMapping(path="update", methods="post")
     * @param RequestInterface $request
     * @return int
     */
    public function update(RequestInterface $request)
    {
        $this->validateParam($request, [
            'account' => 'required',
            'real_name' => 'required',
            'phone' => 'required',
        ]);
        return $this->service->update($request); // TODO: Change the autogenerated stub
    }
}