<?php
declare(strict_types=1);

/**
 * 基类
 */
namespace App\Controller\admin\v1;

use App\Controller\AbstractController;
use App\Middleware\BackendAuthMiddleware;
use App\Service\BaseService;
use Hyperf\Di\Annotation\Inject;

class BaseController extends AbstractController
{
    /**
     * @Inject()
     * @var BaseService
     */
    public $service;

    /**
     * 获取token值
     * @return string
     */
    public function getAuthToken()
    {
        return BackendAuthMiddleware::$authToken;
    }

    /**
     * 获取解析后的token数据
     * @return array
     */
    public function getTokenInfo()
    {
        return BackendAuthMiddleware::$tokenInfo;
    }

    /**
     * 创建token
     * @param $info
     * @return string
     */
    public function createAuthToken($info)
    {
        return BackendAuthMiddleware::createAuthToken($info); // TODO: Change the autogenerated stub
    }

    /**
     * 获取用户id
     * @return mixed
     */
    public function getUserId()
    {
        $info = $this->getTokenInfo();
        return $info['id'];
    }
}