<?php
declare(strict_types=1);

namespace App\Service\Admin;

use App\Model\Entity\Admin;
use App\Service\BaseService;
use App\Utils\Common;
use Hyperf\Di\Annotation\Inject;
use Hyperf\HttpServer\Contract\RequestInterface;

class AdminService extends BaseService
{
    /**
     * @Inject()
     * @var Admin
     */
    public $model;

    /**
     * @param RequestInterface $request
     * @return \Hyperf\Contract\PaginatorInterface
     */
    public function index(RequestInterface $request)
    {
        // 搜索
        if ($request->has('search')) {
            $searchForm = $request->input('search');
            $this->multiSingleTableSearchCondition($searchForm);
        }
        $data = parent::index($request);

        foreach ($data['data'] as $key => &$value) {
            $value['register_time'] = $value['register_time'] ? date('Y-m-d H:i:s', (int)$value['register_time']) : '';
            $value['login_time'] = $value['login_time'] ? date('Y-m-d H:i:s', (int)$value['login_time']) : '';
        }
        return $data;
    }
    /**
     * @param RequestInterface $request
     * @return \Hyperf\Database\Model\Model|\Hyperf\Database\Query\Builder|object|null
     */
    public function show(RequestInterface $request)
    {
        $this->condition = ['id' => $request->input('id')];
        return parent::show($request);
    }

    /**
     * @param RequestInterface $request
     * @return int
     */
    public function update(RequestInterface $request)
    {
        $id = $request->input('id');
        $password = trim($request->input('password'));
        $salt = Common::generateSalt();

        $this->data = [
            'account'   => trim($request->input('account')),
            'real_name' => trim($request->input('real_name')),
            'phone'     => trim($request->input('phone')),
            'status'    => $request->input('status', 0),
            'salt'      => $salt,
            'password'  => Common::generatePasswordHash($password, $salt),
        ];
        $this->condition = ['id' => $id];
        return parent::update($request);
    }

    public function store(RequestInterface $request)
    {
        $salt = Common::generateSalt();
        $password = trim($request->input('password'));
        $ip = $request->getServerParams()['remote_addr'];

        $this->data = [
            'uuid'          => Common::generateSnowId(),
            'account'       => trim($request->input('account')),
            'real_name'     => trim($request->input('real_name')),
            'phone'         => trim($request->input('phone')),
            'status'        => $request->input('status', 0),
            'salt'          => $salt,
            'password'      => Common::generatePasswordHash($password, $salt),
            'register_time' => time(),
            'register_ip'   => $ip,
            'login_time'    => time(),
            'login_ip'      => $ip,
        ];
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param RequestInterface $request
     * @return int
     */
    public function delete(RequestInterface $request)
    {
        $this->condition = ['id' => $request->input('id')];
        return parent::delete($request);
    }
}